Ajoute de summary a API transition
chairemobilite/transition pull request #1042
Opened 2024-09-03 14:31 UTC by GabrielBruno24

La requete API "summary" de trRouting a ajoutee a l'API de transition. Fix: #1031

2024-09-03 15:28 UTC, tahini requested changes

2024-09-03 15:28 UTC, tahini commented on docs/APIv1/summary.yml
> +alternativesParam:
est-ce que `alternatives` est un paramètre de summary?

2024-09-03 15:28 UTC, tahini commented on packages/transition-backend/src/api/public.routes.ts
> +            const body = req.body;
Ici, il faudrait faire une validation des attributs. Ceci est un API depuis l'externe, il pourrait recevoir n'importe quoi. Dans la fonction `/route` en bas, il y a une fonction `validateAndCreateTripRoutingAttributes`, ça prendrait du `validateAndCreateSummaryAttributes` qui retourne les bons attributs, bien typés et validés.

2024-09-05 13:02 UTC, tahini requested changes
Quelques commentaires, surtout pour uniformiser les paramètres entre `route` et `summary`, deux requêtes très liées.

2024-09-05 13:02 UTC, tahini commented on packages/transition-backend/src/api/public.routes.ts
> +            const body: SummaryQueryAttributes = req.body;
Aussi, tu devrais faire la même validation que pour route pour ajouter `properties` aux geojsons, car les librairies qui utilisent l'API (dont QGis) n'ont pas nécessairement de properties dans leur geojson. Mais tout ça peut (et peut-être doit) être fait dans validateAndCreateSummaryAttributes au lieu d'ici, contrairement à `route`.

2024-09-10 19:32 UTC, tahini requested changes
C,est bon, il y aurait juste un type à déplacer et ajouter des tests pour la fonction qui crée les attributs.

2024-09-10 19:32 UTC, tahini commented on packages/chaire-lib-common/src/services/routing/SummaryAttributes.ts
> +export const validateAndCreateSummaryAttributes = (
Je réitère mon souhait de voir des tests pour cette fonction! C,est si facile, en copiant-collant ceux de `validateAndCreateTripRoutingAttributes` dans `RoutingAttributes.test.ts`, plus de 50% sont déjà faits!

2024-09-10 19:32 UTC, tahini commented on packages/chaire-lib-common/src/services/routing/types.ts
> +export type SummaryQueryAttributes = {
Est-ce que ceci est un type pour l'API public d'evolution seulement? Car dans ce fichier, ce sont les types pour les requêtes de routing internes à l'application Transition. Ce serait mieux de mettre ce type directement où il est utilisé dans public.routes.ts. Et aussi ajouter un commentaire pour expliquer son rôle.

2024-09-11 20:07 UTC, tahini approved these changes

2024-09-11 20:09 UTC, greenscientist commented
@GabrielBruno24 please keep the commit message in english

2024-09-11 20:13 UTC, greenscientist requested changes
Apart from the commit message, it looks good.

2024-09-11 20:24 UTC, greenscientist approved these changes

2024-09-12 00:25 UTC, merged