Add a title and icon to the Stop Nodes submenu in the right panel.
chairemobilite/transition pull request #1070
Opened 2024-09-25 19:50 UTC by GabrielBruno24

Fix: #1068

![image](https://github.com/user-attachments/assets/cd5d9199-07ea-451e-8e3a-6f6499f1de49)

2024-09-25 20:06 UTC, tahini commented
Pourrais-tu aussi joindre un screenshot lors de l'édition de noeud, comme ici actuellement:

![Capture d’écran du 2024-09-25 16-06-19](https://github.com/user-attachments/assets/5d116899-d23c-4abf-a99c-e46b6ffa9e87)

2024-09-25 20:09 UTC, tahini requested changes

2024-09-25 20:09 UTC, tahini commented on packages/transition-frontend/src/components/forms/node/TransitNodePanel.tsx
> +            <h3>
Je crois que ce n'est pas exactement à cet endroit qu'il faut mettre ce code. Le code est ok, c'est son emplacement qui pose peut-être problème, il ne faut pas voir ce titre là où d'autres titres existent (comme node edit)

2024-09-25 20:30 UTC, GabrielBruno24 commented on packages/transition-frontend/src/components/forms/node/TransitNodePanel.tsx
> +            <h3>
Je l'ai laissé là et ajouté des conditionnels pour pas qu'il apparaisse pendant le edit et le import. Les boutons par defaut sont là aussi et utilisent une validation conditionnelle aussi donc je pense que malheuresement c'est l`a l'endroit qui fait le plus de sens pour le mettre

2024-09-26 17:31 UTC, tahini approved these changes
Ok, de toute façon, ce composant a tellement de conditionnelles, il y a un TODO en haut pour refactorer ça un jour, allons-y avec une de plus!

2024-09-26 17:31 UTC, merged