Update packages9
chairemobilite/transition pull request #1123
Opened 2024-11-29 18:33 UTC by kaligrafy

2024-11-29 18:40 UTC, tahini commented on packages/chaire-lib-common/src/utils/objects/__tests__/GenericPlaceCollection.test.ts
> +}));
let geokdbushMock = jest.fn()
around: jest.fn().mockImplementation((spatialIndex, x, y, max, res, dist) => geokdbushMock(spatialIndex, x, y, max, blabla))

2024-12-02 14:56 UTC, kaligrafy commented on packages/chaire-lib-common/src/utils/objects/__tests__/GenericPlaceCollection.test.ts
> +}));
fixed

2024-12-02 18:17 UTC, tahini requested changes

2024-12-02 20:39 UTC, tahini approved these changes
Beau cleanup! Et tout semble fonctionner

2024-12-02 20:40 UTC, tahini requested changes

2024-12-02 20:40 UTC, tahini commented on yarn.lock
> +pbf@^3.3.0:
Merge with other

2024-12-02 20:41 UTC, greenscientist commented
@kaligrafy , you should probably put the PR as a draft when you plan to add more commits to it.

2024-12-02 20:57 UTC, tahini approved these changes

2024-12-03 14:30 UTC, merged