dep: Upgrade React to version 19
chairemobilite/transition pull request #1156
Opened 2024-12-16 20:21 UTC by tahini

Upgrade react and other related packages

2024-12-16 20:21 UTC, tahini commented
ça ne fonctionne pas encore: Il reste le register page, qui fonctionne, mais il n'y a pas de redirection une fois le login fait.

2024-12-16 21:50 UTC, GabrielBruno24 reviewed
I haven't looked at everything so far, but I think there should be more info in the commit message, specifically explaining the reason behind some of the more universal changes.

2024-12-17 14:16 UTC, tahini commented on packages/chaire-lib-frontend/src/actions/Auth.tsx
>                      dispatch(login(null, false, false, true));
> Can you also explain in the message why 'await' is added in front of a lot, but not all dispatch()?

@kaligrafy peux-tu expliquer ça aussi?

2024-12-17 16:42 UTC, samuel-duhaime requested changes
Quelques commentaires:
Il faut mettre une majuscule pour les types.
On importe JSX, mais j'ai l'impression que ce n'est pas utilisé. Comment cela ?
Il faut vraiment bien testé les nouvelles middlewares pour les routes comme AdminRoute, il faudrait pas faire une erreur avec cela.

C'est beaucoup plus clair avec les hooks que l'ancienne méthode.
Je crois qu'on devrait continuer à utiliser Redux, ça me semble bien organisé pour ce projet.

2024-12-17 16:42 UTC, samuel-duhaime commented on packages/chaire-lib-frontend/src/components/forms/auth/localLogin/RegisterForm.tsx
> +type FormState = {
Une raison qu'on a enlever le optionel du FormState type?

2024-12-17 16:42 UTC, samuel-duhaime commented on packages/chaire-lib-frontend/src/components/forms/auth/localLogin/RegisterForm.tsx
> +        if (e.key === 'Enter' || e.key === ' ' || e.which === 13 || e.which === 32) {
Écrire un commentaire pour ce if. Pas sûr de savoir c'est quoi les events dans ce cas.

2024-12-17 16:42 UTC, samuel-duhaime commented on packages/chaire-lib-frontend/src/components/forms/auth/passwordless/MagicLinkVerify.tsx
> +            dispatch(startPwdLessVerify(token, location, navigate));
Est-ce qu'on a tester les sideseffect de ce useEffect ? 
Il arrive quand quand on change de page, maintenant ?
Il y a plus de condition aux useEffect. Avant, on avait juste le token.

2024-12-17 16:42 UTC, samuel-duhaime commented on packages/chaire-lib-frontend/src/components/forms/auth/passwordless/PwdLessLoginForm.tsx
> +            return 'auth:invalidEmail';
Pourquoi pas de translation, pour la ligne 39?

2024-12-17 16:42 UTC, samuel-duhaime commented on packages/chaire-lib-frontend/src/components/forms/auth/passwordless/PwdLessLoginForm.tsx
> +        <form className="apptr__form apptr__form-auth" onSubmit={(e) => e.preventDefault()}>
Il arrive rien onSubmit maintenant?
D'habitude, on fait une fonction HandleOnSudmit, avec des actions après e.preventDefautl().

2024-12-17 16:42 UTC, samuel-duhaime commented on packages/chaire-lib-frontend/src/components/input/Button.tsx
> +type anchorAttributesProps = {
Il faut une majuscule pour le nom d'un type.

2024-12-17 16:42 UTC, samuel-duhaime commented on packages/chaire-lib-frontend/src/components/input/InputColor.tsx
> -                    className="_circle-button"
Une raison d'avoir ajouter une class?

2024-12-17 16:42 UTC, samuel-duhaime commented on packages/chaire-lib-frontend/src/components/input/InputMultiselect.tsx
> +type choiceType = {
Majuscule pour le type.

2024-12-17 16:42 UTC, samuel-duhaime commented on packages/chaire-lib-frontend/src/components/input/InputRadio.tsx
> +type choiceType = {
Majuscule pour le type.

2024-12-17 16:42 UTC, samuel-duhaime commented on packages/chaire-lib-frontend/src/components/input/InputRadio.tsx
> +type defaultInputType = {
Same.

2024-12-17 16:42 UTC, samuel-duhaime commented on packages/chaire-lib-frontend/src/components/pages/VerifyPage.tsx
> +            return 'auth:ConfirmationTokenError';
Il n'y a aucun traduction pour ces messages ?

2024-12-17 16:42 UTC, samuel-duhaime commented on packages/chaire-lib-frontend/src/components/routers/AdminRoute.tsx
On a vérifier ceci ? Ça me semble important.

2024-12-17 16:42 UTC, samuel-duhaime commented on packages/chaire-lib-frontend/src/services/dashboard/DashboardContribution.ts
> +import React, { JSX } from 'react';
Est-ce qu'on utilise JSX dans ce fichier ?

2024-12-17 16:42 UTC, samuel-duhaime commented on packages/transition-frontend/src/components/dashboard/TransitionMenuBar.tsx
> -import React from 'react';
On utilise JSX dans ce fichier ?

2024-12-17 16:47 UTC, kaligrafy commented on packages/chaire-lib-frontend/src/actions/Auth.tsx
> +export const startLogout = (navigate: NavigateFunction) => {
It seems navigate is the new way to go, but I can't decide alone

2024-12-17 16:47 UTC, kaligrafy commented on packages/chaire-lib-frontend/src/actions/Auth.tsx
>                      dispatch(login(null, false, false, true));
await removed by @tahini

2024-12-17 16:58 UTC, tahini commented on packages/chaire-lib-frontend/src/components/forms/auth/localLogin/CaptchaComponent.tsx
> +                    name="userCaptcha"
Avant on faisait un mapping de user_captcha à userCaptcha, car le LoginForm avait une fonction séparée par champ. Maintenant, une seule fonction fait tout et s'attend à ce que le nom soit le même que l'état. Bref, c'est plus simple de changer ici, qui n'est de toute façon pas utilisé ailleurs.

2024-12-17 18:12 UTC, tahini commented on packages/chaire-lib-frontend/src/components/forms/auth/localLogin/RegisterForm.tsx
> +type FormState = {
C'est initialisé à '' au lieu de undefined, ça évite un undefined-check pas nécessaire

2024-12-17 18:20 UTC, tahini commented on packages/chaire-lib-frontend/src/components/forms/auth/passwordless/MagicLinkVerify.tsx
> +            dispatch(startPwdLessVerify(token, location, navigate));
J'ai enlevé le navigate et dispatch, je crois que c'est inutile. Mais on pourra tester avec evolution plus tard

2024-12-17 18:29 UTC, tahini commented on packages/chaire-lib-frontend/src/components/pages/VerifyPage.tsx
> +            return 'auth:ConfirmationTokenError';
Non, la traduction se fait par l'appelant

2024-12-17 18:31 UTC, tahini commented on packages/chaire-lib-frontend/src/components/routers/AdminRoute.tsx
L'admin route est utilisé dans evolution. On pourrait probablement l'enlever de transition. je vais ajouter un FIXME

2024-12-17 18:33 UTC, tahini commented on packages/chaire-lib-frontend/src/services/dashboard/DashboardContribution.ts
> +import React, { JSX } from 'react';
oui, pour le type `JSX.Element`

2024-12-17 18:33 UTC, tahini commented on packages/transition-frontend/src/components/dashboard/TransitionMenuBar.tsx
> -import React from 'react';
idem

2024-12-17 18:37 UTC, tahini commented
Changes done, formatting too

2024-12-17 18:44 UTC, samuel-duhaime approved these changes

2024-12-17 19:08 UTC, merged