Remove the maximum duration for accessibilityMap
chairemobilite/transition pull request #1163
Opened 2024-12-17 18:56 UTC by samuel-duhaime

# Pull request
fix: #1063 

## Description
Remove the maximum duration for accessibilityMap

2024-12-17 20:25 UTC, samuel-duhaime commented
## Screenshot
![image](https://github.com/user-attachments/assets/0f727c5e-e8e0-4a09-a038-ecad0a655f50)

2024-12-18 13:52 UTC, tahini requested changes
Can you add the `fixes #1063` in the commit message so we have the link to the issue in the git history

2024-12-18 14:19 UTC, samuel-duhaime commented
> Can you add the `fixes #1063` in the commit message so we have the link to the issue in the git history

Done.

2024-12-18 14:22 UTC, tahini approved these changes

2024-12-18 14:59 UTC, merged