Fix start of osrm-contract
chairemobilite/transition pull request #469
Opened 2022-11-24 19:34 UTC by greenscientist

osrm-contract expect the file prefix when starting. I don't know how the previous command worked

2022-11-25 02:55 UTC, tahini commented
Really? Here's the output of `osrm-contract --help`:

```
$ osrm-contract --help
Usage: osrm-contract <input.osrm> [options]:
[...]
$ osrm-contract --version
v5.27.1
```

2022-11-25 03:10 UTC, greenscientist commented
Yep, that's wrong

2022-11-25 03:46 UTC, tahini commented
What's wrong? the osrm-contract help? If so, since when? Was there a recent change? Would this fix fail on some versions?

It works here because the file is called `${mode}.osrm` after extract, so by setting `[mode]` for `<input.osrm>` it looks for `<mode>.osrm`?

2022-11-25 14:57 UTC, greenscientist commented
So I don't have a file $mode.osrm anymore here. Might be a new version thing. 
I guess we should test with older version of osrm. 
I based this on the output of osrm-extract which said: 
"To prepare the data for routing, run: ./osrm-contract "/app/examples/runtime/osrm/walking/walking""
Need to go check the code histoire in osrm

2022-11-25 15:34 UTC, greenscientist commented
So checking the behavior of the osrm code: 
It takes the parameter and first strip out any known extention before using it as a base path

So basically,   mode.osrm is the same as mode or mode.osm
It does not check that the specific file actually exist, but the rebuild the path to require file base in this base path. 

We can still investigate why we do not have an "mode".osrm file generated anymore. 

Otherwise, we can keep the diff as is, or we can make it so the cmd is with "$mode.osrm" instead of just "$mode".

2022-11-25 16:20 UTC, greenscientist commented
commit 21888334dd1e0fbbd25cc62c725eb33bb7968147
Author: Siarhei Fedartsou <siarhei.fedartsou@gmail.com>
Date:   Fri Sep 30 14:29:10 2022 +0200

    Do not generate intermediate .osrm file in osrm-extract. (#6354)

2022-11-25 16:26 UTC, greenscientist commented
https://github.com/Project-OSRM/osrm-backend/pull/6354

2022-11-25 16:26 UTC, greenscientist commented
it's super confusing and documentation is not well updated yet. 

So I'll change this PR to be mode.osrm

2022-11-25 21:42 UTC, tahini commented
With version 5.25, both the current and preceding version work. With 5.27, the contraction works, but the runtime doesn't. Don't you need to update also the osrm-routed path in the OSRMProcessManager.ts file?

2022-11-25 21:58 UTC, greenscientist commented
hum, probably yes

2022-11-26 00:05 UTC, greenscientist commented
updated, @tahini if you have the chance to test on your side, let me know

2022-11-28 15:35 UTC, tahini requested changes

2022-11-28 15:36 UTC, tahini commented on packages/chaire-lib-backend/src/utils/processManagers/OSRMProcessManager.ts
> +            osrmDirectoryPath + `/${mode}.osrm`,
The other comment applies to this line, not the one from OSRMServicePreparation, sorry.

2022-11-28 17:24 UTC, greenscientist commented on packages/chaire-lib-backend/src/utils/processManagers/OSRMServicePreparation.ts
> +        const osrmProcess = spawn('osrm-contract', [`${mode}.osrm`], {
I guess might have a leftover .osrm file locally that made my test pass.

2022-11-28 18:33 UTC, greenscientist commented on packages/chaire-lib-backend/src/utils/processManagers/OSRMServicePreparation.ts
> +        const osrmProcess = spawn('osrm-contract', [`${mode}.osrm`], {
There's a subtle difference between them. But I've now put the args in a common function.

2022-11-28 18:33 UTC, greenscientist commented
I've made sure to erase the old .osrm in my latest test round.

2022-11-28 19:20 UTC, tahini requested changes
It corresponds to what was working here when tested with both 5.25 and 5.27.1.

Just remove the whitespace so we don't need to add a commit to run `yarn format` later and it's good

2022-11-28 19:20 UTC, tahini commented on packages/chaire-lib-backend/src/utils/processManagers/OSRMProcessManager.ts
> +function getOsrmRoutedStartArgs(osrmDirectory: string, mode: string, port: string) : string[] {
`yarn format` would remove a whitespace before the ':' on this line

2022-11-28 21:31 UTC, greenscientist commented
Fixed my yarn format command, so should be good

2022-11-28 21:32 UTC, tahini approved these changes

2022-11-28 22:37 UTC, merged