auth: remove trailing space in email on login forms
chairemobilite/transition pull request #721
Opened 2023-09-21 21:04 UTC by davidmurray

Fixes #720

2023-09-22 13:01 UTC, tahini reviewed
Thanks, can you add this too the the localLogin's LoginForm and RegisterForm, which will have the same issue (the username should not have spaces either)

2023-09-22 13:19 UTC, davidmurray commented
> Thanks, can you add this too the the localLogin's LoginForm and RegisterForm, which will have the same issue (the username should not have spaces either)

c'est fait!

2023-09-22 14:45 UTC, tahini requested changes

2023-09-22 15:35 UTC, davidmurray commented on packages/chaire-lib-frontend/src/components/forms/auth/localLogin/LoginForm.tsx
> +        const usernameOrEmail = e.target.value.replace(' ', ''); // E-mails and usernames can't have spaces
très bon point! fixed it :)

2023-09-26 14:23 UTC, tahini approved these changes

2023-09-26 14:23 UTC, merged