Add DistanceUnitFormatter and DurationUnitFormatter, two react compon…
chairemobilite/transition pull request #777
Opened 2023-11-22 16:22 UTC by davidmurray

…ents to automatically choose the best unit for a value

They also allow clicking on the values to cycle between the different possible units. Example usage is shown in transit routing output for the walking mode. If code and UX seems satisfactory to you, I will use these components in many other parts of transition.

Demo:

https://github.com/chairemobilite/transition/assets/545502/b3cd1a0c-8627-4cf4-87f6-093245efe79e

Fixes #775

2023-11-22 16:24 UTC, davidmurray commented
I could also add one for speeds : m/s, km/h, mph, etc

2023-11-22 16:32 UTC, kaligrafy approved these changes
Verify code lint though

2023-11-22 16:33 UTC, kaligrafy commented
Very nice!

2023-11-22 17:04 UTC, davidmurray commented
> Verify code lint though

It was better before I ran `yarn format`
If we don't like this formatting we have to change the parameters to prettier eslint!

2023-11-22 18:29 UTC, davidmurray commented
added `SpeedUnitFormatter` too

2023-11-22 20:20 UTC, tahini requested changes
Looks good! You can further type the states though, to limit to the possible values.

2023-11-22 20:20 UTC, tahini commented on packages/chaire-lib-frontend/src/components/pageParts/DistanceUnitFormatter.tsx
> +    const [destinationUnit, setDestinationUnit] = useState<string | undefined>(props.destinationUnit);
Instead of `string`, you can use your destinationUnitOptionType

2023-11-22 20:20 UTC, tahini commented on packages/chaire-lib-frontend/src/components/pageParts/DurationUnitFormatter.tsx
> +    const [destinationUnit, setDestinationUnit] = useState<string | undefined>(props.destinationUnit);
Same here, use destiantionUnitOptionsType

2023-11-22 20:32 UTC, davidmurray commented
@tahini  fixed :)

2023-11-29 02:50 UTC, tahini approved these changes
Thanks!

2023-11-29 03:08 UTC, merged