WIP: Basic endpoints and authentication for public API
chairemobilite/transition pull request #845
Opened 2024-02-12 04:40 UTC by shymkom45

Currently, public REST endpoints are defined in transition-backend in order to access basic transition objects (specifically: paths, nodes, scenarios and available routing modes). Here are a few things to note:

- The API routes reuse logic that was originally defined in [transitObjects.socketRoutes.ts](https://github.com/chairemobilite/transition/commit/7b11825fe402835471205bfa5884dd0264cd76ae), and as such they were moved to a new service called [TransitObjectsDataHandler.ts](https://github.com/chairemobilite/transition/commit/692070bdf212d9f45b952dd2699fb623e9ade989). Comments from the original file were also copied over to the new service (and kept in the original file), so it may be worth checking if they're still relevant.
- A lot of important logic was moved from the socket routes, it may be necessary to properly verify if everything still works as intended. No logic in itself should've been changed, and we have done some manual tests, but this is still something to keep in mind.
- The endpoints for scenarios and available routing modes were mainly added for the QGIS plugin, as it needs that information in order to send a routing request.

Here is what still needs to be done:

- The current authentication system is incomplete. As of now, we send the user's credentials in the body of every HTTP request and then verify them with the database before sending a response. This is why every endpoint in the public API is a post endpoint whereas some of them could be get endpoints. We are currently working on a system where the user can request a token from one endpoint (which is saved in the database), and then pass that token in the header of requests to the rest of the API.
- There are currently few unit tests in place, and some tests may be broken. Any suggestions as for what should be tested would be appreciated.
- We have yet to add OpenAPI documentation for the endpoints.

2024-02-13 15:18 UTC, tahini reviewed
L'approche est bonne! Vous pouvez continuer dans cette direction. Pour l'authentification, il faudrait voir s'il y a autre chose à faire ou une autre approche, si ça fonctionne pour l'instant ok. Vous pouvez regarder du côté des plugins passport s'il y a en a un qui pourrait être utilisé pour une auth avec api token genre. (https://www.passportjs.org/packages/)

2024-02-13 15:18 UTC, tahini commented on packages/chaire-lib-backend/src/api/auth.routes.ts
> -export default <U extends IUserModel>(app: express.Express, authModel: IAuthModel<U>) => {
Ce changement risque d'affecter evolution aussi. C'est correct, mais il faudrait le mentionner dans le commit qui le fait, pour que quand on mettra à jour, la personne pourra voir quoi faire via la commit message sans avoir à chercher pourquoi l'authentification ne fonctionne plus correctement.

2024-02-20 21:23 UTC, vincenthaney commented on packages/chaire-lib-backend/src/api/auth.routes.ts
> -export default <U extends IUserModel>(app: express.Express, authModel: IAuthModel<U>) => {
Le nom du commit a été ajusté. SVP nous confirmer que le nom est suffisamment explicite.

2024-02-23 15:05 UTC, tahini requested changes
Côté logique et code, c'est bien beau, il y a quelques petits détails à fixer et des tests à ajouter.

Savez-vous comment je pourrais tester la fonctionnalité sans frontend, genre avec `curl`. J'ai essayé `curl -d "username=u&password=p" -X POST http://localhost:8080/token`, mais j'ai un bad request (quoique j'ai pas roulé les migrations, je vais attendre vos modifications, mais je me serais attendu à un 500 et non 400).

2024-02-23 16:17 UTC, shymkom45 commented
> Côté logique et code, c'est bien beau, il y a quelques petits détails à fixer et des tests à ajouter.
> 
> Savez-vous comment je pourrais tester la fonctionnalité sans frontend, genre avec `curl`. J'ai essayé `curl -d "username=u&password=p" -X POST http://localhost:8080/token`, mais j'ai un bad request (quoique j'ai pas roulé les migrations, je vais attendre vos modifications, mais je me serais attendu à un 500 et non 400).

@tahini Il faut plutôt faire la commande `curl -d "usernameOrEmail=u&password=p" -X POST http://localhost:8080/token`, c'est de cette manière que le corps de la requête a été défini dans la stratégie local-login de passport.

2024-03-07 16:00 UTC, vincenthaneyvidens commented on packages/chaire-lib-backend/src/models/db/migrations/20221115083601_createUserTbl.ts
> +import { Knex } from 'knex';
Je suis retourné sur la migration précédente et tout semble fonctionner. On va retourner au fichier initial

2024-03-07 16:17 UTC, vincenthaneyvidens commented on packages/chaire-lib-backend/src/models/db/tokens.db.queries.ts
> +        const id = await knex(userTableName)
Je pourrais utiliser find s'il contenait "id", ou je pourrais utiliser "uuid" comme foreign key. Cependant, "uuid" n'est pas "unique"(Voir la migration de user). Je voulais éviter de modifier trop d'entités déjà en place, donc j'ai évité de modifier UserAttributes pour ajouter le champ "id". Qu'est-ce que vous préférez?

2024-03-11 17:41 UTC, tahini requested changes
Quelques petites modifs à faire. Aussi, svp, rouler `yarn format` pour voir les erreurs du linter.

2024-03-12 22:14 UTC, vincenthaneyvidens commented on packages/chaire-lib-backend/src/models/db/tokens.db.queries.ts
> +        const id = await knex(userTableName)
@tahini Ceci n'a pas été implémenté, j'attends votre réponse. Êtes-vous satisfaits de l'implémentation actuelle?

2024-03-12 22:19 UTC, vincenthaneyvidens commented on packages/chaire-lib-backend/src/models/db/tokens.db.queries.ts
> -        console.error(`cannot get token by ID ${user_id} (knex error: ${error})`);
J'ai modifié les erreurs. Cependant, les codes d'erreurs sont mis à "ERRORCODE". Je ne trouve pas la définition pour les codes d'erreurs comme celui de "DBQDSC0001".

2024-03-13 12:53 UTC, tahini commented on packages/chaire-lib-backend/src/models/db/tokens.db.queries.ts
> -        console.error(`cannot get token by ID ${user_id} (knex error: ${error})`);
haha on se fait prendre! Il n'y a pas de définition. Perso, pour ces codes d'erreurs, quand j'ajoute un fichier de requête BD, je trouve qqc qui a l'air cute pour la fonctionnalité et ensuite un chiffre pour avoir un identifiant unique par fonction. Ici, j'aurais mix DBUTK0001, pour "user token" genre. Mais honnêtement, on ne l'utilise pas, sauf que la classe TrError en prend un... Peut-être qu'on va l'utiliser un jour...

2024-03-13 14:00 UTC, tahini requested changes
ça y est presque, il resterait à ajouter un try/catch sur toutes les fonctions BD de token.

Ensuite cette PR sera prête à être mergée.

2024-03-13 14:00 UTC, tahini commented on packages/chaire-lib-backend/src/models/db/tokens.db.queries.ts
> +    const response = await knex(tableName).where({ user_id });
pour `getById` et `getUserByToken`, il faudrait avoir un try/catch pour toute la fonction, comme vous l'avez fait pour `getOrCreate`. Les fonctions BD peuvent thrower une erreur à n'importe quel moment et le try/catch de la fonction permet de contrôler l'erreur lancé ultimement, en envoyant une seule TrError avec le code d'erreur spécifique pour cette fonction.

2024-03-13 14:00 UTC, tahini commented on packages/chaire-lib-backend/src/models/db/tokens.db.queries.ts
> +        throw new TrError(
Puisque vous avez lancé des TrError plus haut, vous pouvez juste la relancer donc `throw TrError.isTrError(error) ? error : new TrError(...)`

2024-03-13 14:00 UTC, tahini commented on packages/transition-backend/src/api/__tests__/public.routes.test.ts
> +        transitObjectDataHandlers.nodes.geojsonCollection! = jest.fn();
Pour être ben ben sur la coche, je vous dirais ici d'ajouter un mockResolvedValue(qqc) pour les fonctions de transitObjectDataHandlers et valider que la réponse est bien identique

2024-03-13 21:33 UTC, vincenthaney commented on packages/chaire-lib-backend/src/models/db/tokens.db.queries.ts
> +    const response = await knex(tableName).where({ user_id });
Ahh je comprends mieux pourquoi la gestion d'erreur est comme elle l'est maintenant!

2024-03-13 22:10 UTC, vincenthaney commented on packages/chaire-lib-backend/src/models/db/tokens.db.queries.ts
> +    const response = await knex(tableName).where({ user_id });
Pour celui-ci, j'ai une linting error si je mets ceci dans un try/catch. j'ai mis un es-lint-disable pour le block de code.

2024-03-14 13:03 UTC, tahini approved these changes
C'est bon, il resterait quelques petits commentaires, que vous pouvez faire maintenant (ça va re-triggerer le docker build, qui a fait un timeout hier, pour qu'il passe).

Pour le merge, on va faire un squash and merge, qui va donner un seul commit. Je prendrais le texte d'intro de cette PR comme commentaire. Si je comprends bien, dans les éléments qu'il restait à faire, vous aviez 3 points, les 2 premiers sont complétés et il ne reste que le dernier, soit la documentation de l'API?

2024-03-14 13:08 UTC, tahini commented
En fait, avant de pouvoir merger, pourriez-vous faire un rebase de votre branche sur les changements les plus récents pour vous assurer qu'il n'y a pas de conflits?

Pour faire un rebase sur `main`:

```
git checkout main
git pull (en vous assurant que ça pull bien d'upstream et non de votre repo)
git checkout basic-endpoints
git rebase main
git push -f <remote> basic-endpoints
```

2024-03-14 13:23 UTC, tahini commented on packages/transition-backend/src/api/public.routes.ts
> +        const token = await tokensDbQueries.getOrCreate(req.body.usernameOrEmail);
Je viens d'essayer cette requête. J'avais roulé l'ancienne migration (quand user_id s'appeler id). Bref, cette requête a lancé une erreur et ma commande `curl` n'a jamais terminé. Il faudrait ajouter un try/catch ici et retourner une erreur 500 en cas de problème.

Ce serait à fixer soit maintenant ou comme bug fix après le merge selon ce qui vient en premier...

2024-03-14 13:34 UTC, tahini commented on packages/chaire-lib-backend/src/config/auth/localLogin.config.ts
> +                return done(err);
Ici, peut-être remplacer par qqc de générique, genre simplement 'Unauthorized' ou `InvalidToken`. L'utilisateur n'a pas besoin d'avoir le message d'erreur complet. Voici ce que j'obtiens avec un token invalide:

```
<pre>Error: No such id in tokens table.<br> &nbsp; &nbsp;at /home/gbastien/Mobilité/sources/transition/packages/chaire-lib-backend/lib/models/db/tokens.db.queries.js:87:19<br> &nbsp; &nbsp;at Generator.next (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at fulfilled (/home/gbastien/Mobilité/sources/transition/packages/chaire-lib-backend/lib/models/db/tokens.db.queries.js:5:58)<br> &nbsp; &nbsp;at process.processTicksAndRejections (node:internal/process/task_queues:95:5)</pre>
```

2024-03-18 18:09 UTC, merged