Added documentation for public API endpoints with Redocly and added explicit response types for endpoints
chairemobilite/transition pull request #902
Opened 2024-04-12 16:03 UTC by shymkom45

The documentation for the public API is in the docs/APIv1 folder in various YAML files written under the OpenAPI specification. This documentation can be displayed in a Redocly UI using the docs/index.html file. The response formats for all API endpoints has also been made more explicit in the code through the use of classes inheriting from APIResponseBase and the definition of response types.

2024-04-12 16:05 UTC, shymkom45 commented
Nous avons fait un déploiement de la documentation avec GitHub Pages sur notre fork pour avoir un aperçu. Vous pouvez le voir ici: [](https://mathildebrosseau.github.io/transition-api/)

2024-04-15 13:57 UTC, tahini requested changes
Excellent pour la doc! Et les classes de conversion de résultat à réponse API, c'est super, car l'API ne dépend plus des calculs internes.

Comme changement à faire pour accepter cette PR, svp, juste enlever les strokes de la réponse d'accessibilité.


Si vous avez le temps, il serait bien d'ajouter des tests pour les classes `*APIResponse`. Pour ce faire, il faut éviter de générer des valeurs de tests qui vont faire que le test va toujours passer même si on change l'API, alors, soit il faut trouver des valeurs de tests déjà présentes pour les tests des calculs et cartes d'accessibilité, qui seront forcément modifiées si on change les fonctions de calculs (donc feront naturellement échouer vos tests par extension s'il y lieu), ou soit vous typez l'input avec le bon type (genre `ReturnType<la fonction de calcul>`).

Si vous n'avez pas le temps d'ajouter des tests, svp ouvrir un issue à cette fin.

2024-04-15 13:57 UTC, tahini commented on packages/transition-backend/src/api/public/AccessibilityMapAPIResponse.ts
> +            strokes:
Honnêtement, je pense que strokes, ce n'est pas nécessaire. C'est très lié avec mapbox pour afficher les contours du polygone. Je crois que la PR qui passe à deck.gl élimine tous ces layers de strokes, donc pour l'API, vous pouvez l'enlever. juste les polygones, c'est ben correct.

2024-04-15 19:51 UTC, tahini approved these changes
ça me va, merci!

@greenscientist veux-tu faire une review là-dessus aussi?

2024-04-15 20:01 UTC, greenscientist commented
J'ai regardé vite vite. Y'a de la doc, je suis content. 

C'est documenté comment on génère la doc ou bien c'est un truc automagique de github?

2024-04-15 20:02 UTC, greenscientist commented
Peut-etre pour une discussion plus tard: pour le token, on ne devrait pas plutot utiliser /api/token comme path plutot que /token directement?

2024-04-15 20:07 UTC, tahini commented
Pour la génération de doc, on le fait déjà pour trRouting, c'est semi-automagique, faut juste se rappeler où aller cocher une case. @shymkom45 comme vous l,avez fait récemment, c'est probablement plus frais à votre mémoire. On peut regarder ça vitement demain si c'est pas fait d'ici là.

2024-04-15 20:08 UTC, merged

2024-04-15 22:31 UTC, shymkom45 commented
Oui c'est très simple à déployer avec GitHub Pages, on peut s'en parler demain!