pyTransition: Added pyTransition source code
chairemobilite/transition pull request #910
Opened 2024-04-18 19:08 UTC by mathildebrosseau

2024-04-23 17:26 UTC, tahini commented on pyTransition/.gitignore
> +# Byte-compiled / optimized / DLL files
Le .gitignore peut être enlevé de ce répertoire. Par contre, il faudrait s'assurer que tout le contenu relatif à python est ajouté au .gitignore du projet

2024-04-29 13:52 UTC, greenscientist commented on pyTransition/.gitignore
> +# Byte-compiled / optimized / DLL files
Je me demande si c'est pas  mieux de garder le contenu python du ignore dans ce répertoire spécifique plutot qu'à la racine

2024-05-01 18:24 UTC, tahini requested changes
C'est bon, on va la prendre comme ça. Je vais refaire la PR par contre pour ajouter @manelkdm dans le co-authored-by pour que vous ayiez toutes les deux cette contribution à votre actif.

2024-05-01 18:42 UTC, tahini commented
Replaced with #925

2024-05-01 18:42 UTC, closed without merging